// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh4lVhufQ68_UbVA1s_tSSyMYsdJBzfgI',
    appId: '1:372103305137:android:3c1222ca77a9014f418f90',
    messagingSenderId: '372103305137',
    projectId: 'appdating-51ba1',
    storageBucket: 'appdating-51ba1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8n6iRf77F_F5OPAW7_PrPPX-UMYzMI28',
    appId: '1:372103305137:ios:4d1f251167dcf4bd418f90',
    messagingSenderId: '372103305137',
    projectId: 'appdating-51ba1',
    storageBucket: 'appdating-51ba1.appspot.com',
    androidClientId: '372103305137-3nq75jm4pikg3ltid1rrphe36fpih281.apps.googleusercontent.com',
    iosClientId: '372103305137-ka68qvesomqetbnpm15hh2ueojns45d4.apps.googleusercontent.com',
    iosBundleId: 'com.example.appdatting',
  );
}
